### ISSUE TITLE
siteClean task not listed

### ISSUE THREAD

**Issue by russel** [breskeby/GradleSite#1]
As at 47ab9f1a407b6fd28c26361177d273c1d26d8d40, when doing "gradle tasks", the site task is listed under "Other tasks", but the siteClean task appears not to be listed.

**Comment by breskeby** [comment]
hey russel. thanks for your efforts. will take a look at the issues you list here soon

**Comment by breskeby** [comment]
the cleanSite task is added via gradle rules. the "tasks" output is right when writing:
"Pattern: clean<TaskName>: Cleans the output files of a task."
Maybe I should not explicitly mention the cleanSite task. as it is a buildin gradle feature to add this task to the Site task.

**Comment by russel** [comment]
Or say that that task is provided via the rules system and so isn't listed separately?

Might be worth adding a comment line to the site entry as well?

I'll close this issues as "Not a Bug".
